name: Addition Workflow

on: [push]

jobs:
  run-addition:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run addition code
      run: python addition.py
